### ISSUE TITLE
useClientEffectQrl is not a function

### ISSUE THREAD

**Issue by rishabhnayak** [qwik-design/qwik-lottie#3]
Code Not Working On  Above Qwik version 0.25.0

**Comment by notdezzi** [comment]
Hey, in the "lottie.tsx" you have to change "useClientEffect" to "useVisibleTask". Thatll fix your problem

**Comment by rishabhnayak** [comment]
great
Thanks for the tip!

**Comment by alihammad99** [comment]
@notdezzi  Hi, I have the same issue.
I don't have "lottie.tsx" file
